dist: trusty
language: python
python:
  - "3.6"
  - "3.6-dev"
#  - "3.7-dev"
#  - "nightly"
# command to install dependencies
install:
  - pip install -e .
  - pip install pytest-asyncio
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install pycodestyle
# command to run tests
script:
  - pytest --cov=aiorpcx
  - pycodestyle --exclude=conf.py aiorpcx docs
after_success: coveralls
